camera_1:
  node_name: "camera_1"
  camera_id: 1
camera_2:
  node_name: "camera_1"
  camera_id: 2
camera_3:
  node_name: "camera_1"
  camera_id: 3
camera_4:
  node_name: "camera_1"
  camera_id: 4
camera_5:
  node_name: "camera_1"
  camera_id: 5
camera_6:
  node_name: "camera_1"
  camera_id: 6

